name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build PDF
        uses: docker://gmacster/lilypond:latest
        with:
          args: lilypond --verbose src/marches-2-4/cowal-gathering.ly

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cowal-gathering
          path: cowal-gathering.pdf
